### ISSUE TITLE
Is there any way to view documentation? 

### ISSUE THREAD

**Issue by fekie** [rust3ds/ctru-rs#144]
I'm new to embedded Rust. I see that when I hover over functions I can see the documentation of them. However, as there isn't a docs.rs page and `cargo doc` doesn't work, I'm not sure how I could read the full documentation.

**Comment by Meziu** [comment]
We are working toward publishing the full documentation via github pages, since there are going to be issues with `docs.rs` once the crate gets uploaded to `crates.io`.

Either way, you can locally clone this repo and run `cargo 3ds doc —open` in its root folder.

If you still need to install `cargo-3ds` and the rest of the toolchain, have a look at our [wiki](https://github.com/rust3ds/ctru-rs/wiki).

**Comment by ian-h-chamberlain** [comment]
As it happens, I just got this working for [`citro3d-rs`](https://rust3ds.github.io/citro3d-rs/)! I was using that repo as a testing ground to get docs working so I might as well make a similar PR for this crate now that it works — this should keep the docs up-to-date with `master` and make it easier to link to certain APIs etc. 

I should just be able to copy the implementation from there so I'll try to put something up shortly.

**Comment by Meziu** [comment]
Damn @ian-h-chamberlain, you are working a lot on the project. This is incredible!

**Comment by Meziu** [comment]
@fekie Here it is! https://rust3ds.github.io/ctru-rs/crates/ctru

**Comment by fekie** [comment]
> @fekie Here it is! https://rust3ds.github.io/ctru-rs/crates/ctru

alright tyyyy
