### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by STBrian** [rust3ds/ctru-rs#176]
I need help, I'm just trying to test this project, but every time I try to build my test project it tells me this. Sorry if this becomes obvious, I'm new to this, and I'm looking for help in several places and can't find anything.
```
No pre-build std found, using build-std
Warning: unable to check if `ctru` debuginfo should be linked: `ctru-sys` not found
   Compiling hello-world v0.1.0 (/home/.../Documentos/3ds-rust/hello-world)
error: linker `arm-none-eabi-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `hello-world` (bin "hello-world" test) due to 1 previous error

```
I would be glad if someone could help me

**Comment by Meziu** [comment]
If you don’t have the tools on your system, it’s because you still need to install the devkitARM toolchain (there’s our guide [here](https://github.com/rust3ds/ctru-rs/wiki/Getting-Started#install-the-devkitarm-toolchain)).

If you do have that installed, it might be that the tool isn’t on the system’s PATH (you should refer to [this](https://github.com/rust3ds/ctru-rs/wiki/Getting-Started#link-the-tools-to-the-system) part specifically).

Please, if possible, follow the instructions in te repository’s [README](https://github.com/rust3ds/ctru-rs?tab=readme-ov-file#ctru-rs) and the [Wiki](https://github.com/rust3ds/ctru-rs/wiki) before working with our projects, as most of what you’ll find here doesn’t adhere with the normal Rust ecosystem.

**Comment by STBrian** [comment]
I'm very sorry, I already had everything installed, but after checking better, I realized that I actually didn't have $DEVKITARM/bin in the path. I already added it and everything seems to be working fine. I'm sorry I realized until now. Also, thanks for responding quickly.
