### ISSUE TITLE
Update ctru-rs for the latest libctru release

### ISSUE THREAD

**Issue by Meziu** [rust3ds/ctru-rs#91]
`libctru` just released the latest 2.1.2 version: https://github.com/devkitPro/libctru/releases/tag/v2.1.2.

There have been numerous changes, but the one that influences us the most is the native addition of `clock_gettime`. We should update our repos accordingly.

Furthermore, @ian-h-chamberlain's thread changes have been released! Does this help with the `thread_local`PRs?

PRs to be merged:

- [x] #90
- [x] https://github.com/rust3ds/rust-linker-fix-3ds/pull/15
- [x] https://github.com/rust3ds/pthread-3ds/pull/20

**Comment by ian-h-chamberlain** [comment]
Yes, we should be able to re-enable `#[thread_local]` finally on Rust main now! I also wonder if `citro3d-rs` will need any updates to account for the changes made in `ctru-sys`... If I have some time this weekend I'll take a look at both of those and will link here once I have PRs.

It looks like some of the APIs changed to use `size_t` instead of `u32` now too? Nice to have less `as` casts

**Comment by Meziu** [comment]
@rust3ds/active Great stuff. I’ve merged the changes, I remind everybody to do `(dkp-)pacman -Syu` `cargo clean` and `cargo update` before using the toolchain. 😃
